#!/bin/bash
#SBATCH -J CAS10
#SBATCH -N 1           # nodes number (=NBP)   
#SBATCH -n 1         # CPUs number (on all nodes) (=NBP*TPN) 
#SBATCH -o CAS10.eo%j   #
#SBATCH -e CAS10.eo%j   #
#SBATCH -t 00:30:00    # time limit

# Echo des commandes

ulimit -c 0
ulimit -s unlimited

# Nom de la machine
hostname


. /home/cnrm_other/ge/mrmc/jacqueth/MNH-V5-6-2/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-2tracers_SBGinOUT-MPIAUTO-O3
#. /home/jacqhugo/MNH-V5-6-2/conf/profile_mesonh-LXgfortran-R8I4-MNH-V5-6-2-2tracers_SBGinOUT-MPIAUTO-DEBUG

# Arrete du job des la premiere erreur
set -e

export MPIRUN="Mpirun -np 1" # 512

#export TIMEOUT="timelimit -t 7200"

ls -lrt

#${TIMEOUT} time ${MPIRUN} PREP_IDEAL_CASE${XYZ} # MCP
time ${MPIRUN} PREP_IDEAL_CASE${XYZ} # belenos
#${TIMEOUT} time ${MPIRUN} idrmem PREP_IDEAL_CASE${XYZ} PAS EN PRODUCTION !!!
mv OUTPUT_LISTING1  OUTPUT_LISTING1_ideal
ls -lrt

rm -f file_for_xtransfer pipe_name

ls -lrt
echo "Exit status is" $? 

