#!/bin/bash
#SBATCH -J INIT
#SBATCH -N 1           # nodes number (=NBP)   
#SBATCH -n 1         # CPUs number (on all nodes) (=NBP*TPN) 
#SBATCH -o INIT.eo%j   #
#SBATCH -e INIT.eo%j   #
#SBATCH -t 00:30:00    # time limit


set -x # Echo des commandes
ulimit -c 0
ulimit -s unlimited
set -e # Arret du job des la premiere erreur

# Nom de la machine
hostname

# HERE CHANGE THE PROFILE WITH YOURS
. /home/cnrm_other/ge/mrmc/jacqueth/MNH-V5-6-2/conf/profile_mesonh-LXifort-R8I4-MNH-V5-6-2-2tracers_SBGinOUT-MPIAUTO-O3
#. /home/jacqhugo/MNH-V5-6-2/conf/profile_mesonh-LXgfortran-R8I4-MNH-V5-6-2-2tracers_SBGinOUT-MPIAUTO-DEBUG

export MPIRUN="Mpirun -np 1"
#export TIMEOUT="timelimit -t 7200"

ls -lrt

#${TIMEOUT} time ${MPIRUN} PREP_IDEAL_CASE${XYZ} #local cmd
time ${MPIRUN} PREP_IDEAL_CASE${XYZ} #belenos cmd

mv OUTPUT_LISTING1  OUTPUT_LISTING1_ideal
ls -lrt

rm -f file_for_xtransfer pipe_name

ls -lrt
echo "Exit status is" $? 

